# Generated by Django 4.2.4 on 2023-09-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_thumb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
